name: ci

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - README.md
  pull_request:
    branches: [main]
    paths-ignore:
      - README.md

jobs:
  run:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 25

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.0

      - name: install
        run: bun install

      - name: check linting
        run: bun run check
